version: '3.8'

services:
  backend:
    build:
      context: ./backend
    ports:
      - "5001:5000"
    volumes:
      - ./backend:/app
    environment:
      - FLASK_APP=wsgi.py
      - FLASK_ENV=development
      - PYTHONPATH=/app
    command: flask run --host=0.0.0.0"

  frontend:
    build:
      context: ./frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
    environment:
      - REACT_APP_API_URL=http://127.0.0.1:5001/api
    command: npm start
